const express=require("express"),session=require("express-session"),fs=require("fs");
const app=express(),PORT=process.env.PORT||10000;
const DB="./links.json";
const ADMIN_USER=process.env.ADMIN_USER||"admin",ADMIN_PASS=process.env.ADMIN_PASS||"admin123",SESSION_SECRET=process.env.SESSION_SECRET||"change-this-secret";
app.use(express.urlencoded({extended:true}));app.use(express.json());
app.use(session({secret:SESSION_SECRET,resave:false,saveUninitialized:false,cookie:{httpOnly:true,secure:process.env.NODE_ENV==="production",maxAge:86400000}}));

if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({profile:{name:"ROXE",bio:"All my links in one place.",avatar:"",theme:"purple"},links:[]},null,2));
function read(){let d=JSON.parse(fs.readFileSync(DB));if(Array.isArray(d)){d={profile:{name:"ROXE",bio:"All my links in one place.",avatar:"",theme:"purple"},links:d}};d.profile ||= {name:"ROXE",bio:"All my links in one place.",avatar:"",theme:"purple"};d.links ||= [];return d}
function save(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}
function esc(x=""){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function auth(req,res,next){if(req.session.admin)return next();res.redirect("/admin/login")}

const css=`
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#fff}
body{background:#05030d;overflow-x:hidden}.bg{position:fixed;inset:0;z-index:-3;background:radial-gradient(circle at 20% 10%,#641cff35,transparent 35%),radial-gradient(circle at 80% 70%,#00d9ff20,transparent 35%),#05030d}
.orb{position:fixed;border-radius:50%;filter:blur(70px);opacity:.35;z-index:-2;animation:float 9s ease-in-out infinite}.o1{width:260px;height:260px;background:#7b2cff;top:5%;left:-80px}.o2{width:220px;height:220px;background:#00d9ff;right:-70px;top:40%;animation-delay:-3s}.o3{width:180px;height:180px;background:#ff2fb3;left:35%;bottom:-70px;animation-delay:-6s}
@keyframes float{50%{transform:translate(35px,-30px) scale(1.15)}}canvas{position:fixed;inset:0;z-index:-1;pointer-events:none}
.wrap{width:min(680px,92%);margin:auto;padding:55px 0 45px}.profile{text-align:center;animation:up .8s ease}.avatar{width:105px;height:105px;margin:auto;border-radius:32px;display:flex;align-items:center;justify-content:center;font-size:42px;font-weight:900;background:linear-gradient(135deg,#8b5cf6,#06b6d4);box-shadow:0 15px 55px #7c3aed55;overflow:hidden}.avatar img{width:100%;height:100%;object-fit:cover}.name{font-size:34px;font-weight:900;margin:17px 0 5px;letter-spacing:-1px}.bio{color:#b9b3ca;font-size:15px;margin:0 auto 20px;max-width:500px}
.social{display:flex;justify-content:center;gap:10px;margin-bottom:27px}.social a{width:40px;height:40px;border-radius:14px;display:grid;place-items:center;color:#fff;text-decoration:none;background:#ffffff0c;border:1px solid #ffffff18;backdrop-filter:blur(15px);transition:.25s}.social a:hover{transform:translateY(-4px) rotate(3deg);background:#ffffff18}
.links{display:grid;gap:15px}.card{position:relative;display:flex;align-items:center;gap:15px;min-height:76px;padding:13px 17px;border:1px solid #ffffff18;border-radius:23px;background:linear-gradient(110deg,#ffffff12,#ffffff06);backdrop-filter:blur(22px);box-shadow:0 15px 50px #0005;overflow:hidden;text-decoration:none;color:#fff;transition:transform .3s,box-shadow .3s,border-color .3s;animation:up .65s ease both}.card:before{content:"";position:absolute;inset:0;background:linear-gradient(110deg,transparent 25%,#ffffff18 50%,transparent 75%);transform:translateX(-120%);transition:.7s}.card:hover{transform:translateY(-5px) scale(1.012);border-color:#ffffff38;box-shadow:0 22px 65px #0008}.card:hover:before{transform:translateX(120%)}.icon{width:48px;height:48px;border-radius:16px;display:grid;place-items:center;font-size:24px;background:#ffffff10;border:1px solid #ffffff15;flex:none}.ct{min-width:0;flex:1}.title{font-weight:800;font-size:16px}.desc{color:#aaa3b8;font-size:12px;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.arrow{font-size:22px;color:#aaa;transition:.25s}.card:hover .arrow{transform:translateX(5px);color:#fff}.footer{text-align:center;color:#625d70;font-size:11px;margin-top:28px}
@keyframes up{from{opacity:0;transform:translateY(25px)}to{opacity:1;transform:none}}
.adminbody{background:#08060f}.panel{width:min(1000px,94%);margin:35px auto}.top{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:25px}.top h1{margin:0}.box{background:#ffffff09;border:1px solid #ffffff14;border-radius:20px;padding:22px;margin-bottom:18px;backdrop-filter:blur(18px)}input,textarea,select{width:100%;padding:13px 14px;margin:7px 0 13px;border-radius:12px;border:1px solid #ffffff18;background:#05040b;color:#fff;outline:none}textarea{min-height:80px;resize:vertical}label{font-size:12px;color:#aaa}button,.btn{border:0;border-radius:12px;padding:11px 16px;background:linear-gradient(135deg,#7c3aed,#0891b2);color:#fff;font-weight:800;text-decoration:none;cursor:pointer}.danger{background:#b42335}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.linkrow{display:grid;grid-template-columns:55px 1fr auto;gap:13px;align-items:center;padding:13px;border:1px solid #ffffff12;border-radius:16px;margin-top:10px}.mini{width:50px;height:50px;display:grid;place-items:center;border-radius:14px;background:#ffffff0d;font-size:23px}@media(max-width:600px){.wrap{padding-top:35px}.name{font-size:29px}.row{grid-template-columns:1fr}.top{align-items:flex-start}.linkrow{grid-template-columns:45px 1fr}.linkrow .actions{grid-column:2}.orb{filter:blur(50px)}}`;

app.get("/",(req,res)=>{
const d=read(),p=d.profile;
let links=d.links.map((l,i)=>`<a class="card" style="animation-delay:${i*70}ms" href="/go/${l.id}"><div class="icon">${esc(l.icon||"🔗")}</div><div class="ct"><div class="title">${esc(l.title)}</div><div class="desc">${esc(l.description||"Tap to open")}</div></div><div class="arrow">›</div></a>`).join("");
res.send(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.name)} — Links</title><style>${css}</style></head><body><div class="bg"></div><div class="orb o1"></div><div class="orb o2"></div><div class="orb o3"></div><canvas id="c"></canvas><main class="wrap"><section class="profile"><div class="avatar">${p.avatar?`<img src="${esc(p.avatar)}">`:esc(p.name?.[0]||"R")}</div><div class="name">${esc(p.name)}</div><p class="bio">${esc(p.bio)}</p><div class="social">${p.instagram?`<a href="${esc(p.instagram)}" target="_blank">◎</a>`:""}${p.youtube?`<a href="${esc(p.youtube)}" target="_blank">▶</a>`:""}${p.discord?`<a href="${esc(p.discord)}" target="_blank">◈</a>`:""}</div></section><section class="links">${links||'<div class="bio">No links added yet.</div>'}</section><div class="footer">© ${new Date().getFullYear()} ${esc(p.name)} · All links in one place</div></main><script>
const c=document.getElementById("c"),x=c.getContext("2d");let w,h,pts=[];function resize(){w=c.width=innerWidth;h=c.height=innerHeight;pts=Array.from({length:Math.min(75,Math.floor(w/12))},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.25,r:Math.random()*1.5+.4}))}resize();addEventListener("resize",resize);function draw(){x.clearRect(0,0,w,h);for(const p of pts){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fillStyle="rgba(255,255,255,.35)";x.fill()}requestAnimationFrame(draw)}draw();
</script></body></html>`)});

app.get("/go/:id",(req,res)=>{let d=read(),l=d.links.find(x=>String(x.id)===String(req.params.id));if(!l)return res.redirect("/");l.clicks=(l.clicks||0)+1;save(d);res.redirect(l.url)});

app.get("/admin/login",(req,res)=>res.send(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Login</title><style>${css}.login{width:min(390px,92%);margin:12vh auto}</style></head><body class="adminbody"><div class="login box"><h1>🔐 Admin</h1><form method="post"><label>Username</label><input name="user" required><label>Password</label><input type="password" name="pass" required><button>Login</button></form></div></body></html>`));
app.post("/admin/login",(req,res)=>{if(req.body.user===ADMIN_USER&&req.body.pass===ADMIN_PASS){req.session.admin=true;return res.redirect("/admin")}res.status(401).send("Invalid login")});

app.get("/admin",(req,res)=>{if(!req.session.admin)return res.redirect("/admin/login");let d=read(),p=d.profile;
let rows=d.links.map(l=>`<div class="linkrow"><div class="mini">${esc(l.icon||"🔗")}</div><form method="post" action="/admin/edit/${l.id}" style="display:contents"><div><input name="title" value="${esc(l.title)}" placeholder="Title"><input name="url" value="${esc(l.url)}" placeholder="URL"><input name="description" value="${esc(l.description||"")}" placeholder="Description"></div><div class="actions"><input name="icon" value="${esc(l.icon||"🔗")}" style="width:70px"><button>Save</button></form><form method="post" action="/admin/delete/${l.id}" style="display:inline"><button class="danger" onclick="return confirm('Delete this link?')">Delete</button></form><div>Clicks: ${l.clicks||0}</div></div></div>`).join("");
res.send(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>LinkHub Admin</title><style>${css}</style></head><body class="adminbody"><div class="panel"><div class="top"><h1>⚡ LinkHub</h1><div><a class="btn" href="/" target="_blank">View Site</a> <a class="btn" href="/admin/logout">Logout</a></div></div><div class="box"><h2>Profile</h2><form method="post" action="/admin/profile"><div class="row"><div><label>Name</label><input name="name" value="${esc(p.name)}"><label>Avatar URL</label><input name="avatar" value="${esc(p.avatar||"")}"></div><div><label>Bio</label><textarea name="bio">${esc(p.bio)}</textarea><label>Instagram URL</label><input name="instagram" value="${esc(p.instagram||"")}"><label>YouTube URL</label><input name="youtube" value="${esc(p.youtube||"")}"><label>Discord URL</label><input name="discord" value="${esc(p.discord||"")}"></div></div><button>Update Profile</button></form></div><div class="box"><h2>➕ Add Link</h2><form method="post" action="/admin/add"><div class="row"><div><label>Title</label><input name="title" required placeholder="My LinkPays"><label>URL</label><input name="url" required placeholder="https://..."></div><div><label>Icon</label><input name="icon" value="🔗"><label>Description</label><input name="description" placeholder="Open my link"></div></div><button>Add Link</button></form></div><div class="box"><h2>🔗 Your Links (${d.links.length})</h2>${rows||"<p class=bio>No links yet.</p>"}</div></div></body></html>`)}); 

app.post("/admin/profile",auth,(req,res)=>{let d=read();d.profile={...d.profile,name:req.body.name||"ROXE",bio:req.body.bio||"",avatar:req.body.avatar||"",instagram:req.body.instagram||"",youtube:req.body.youtube||"",discord:req.body.discord||""};save(d);res.redirect("/admin")});
app.post("/admin/add",auth,(req,res)=>{let d=read();d.links.push({id:Date.now(),title:req.body.title,url:req.body.url,description:req.body.description||"",icon:req.body.icon||"🔗",clicks:0});save(d);res.redirect("/admin")});
app.post("/admin/edit/:id",auth,(req,res)=>{let d=read(),l=d.links.find(x=>String(x.id)===String(req.params.id));if(l){l.title=req.body.title;l.url=req.body.url;l.description=req.body.description||"";l.icon=req.body.icon||"🔗";save(d)}res.redirect("/admin")});
app.post("/admin/delete/:id",auth,(req,res)=>{let d=read();d.links=d.links.filter(x=>String(x.id)!==String(req.params.id));save(d);res.redirect("/admin")});
app.get("/admin/logout",(req,res)=>req.session.destroy(()=>res.redirect("/admin/login")));
app.listen(PORT,()=>console.log("LinkHub running on port "+PORT));
